*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZTEST_V.........................................*
FORM GET_DATA_ZTEST_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTEST WHERE
(VIM_WHERETAB) .
    CLEAR ZTEST_V .
ZTEST_V-MANDT =
ZTEST-MANDT .
ZTEST_V-ID =
ZTEST-ID .
ZTEST_V-VERZE =
ZTEST-VERZE .
ZTEST_V-MATNR =
ZTEST-MATNR .
<VIM_TOTAL_STRUC> = ZTEST_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZTEST_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZTEST_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZTEST_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTEST WHERE
  ID = ZTEST_V-ID AND
  VERZE = ZTEST_V-VERZE .
    IF SY-SUBRC = 0.
    DELETE ZTEST .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTEST WHERE
  ID = ZTEST_V-ID AND
  VERZE = ZTEST_V-VERZE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTEST.
    ENDIF.
ZTEST-MANDT =
ZTEST_V-MANDT .
ZTEST-ID =
ZTEST_V-ID .
ZTEST-VERZE =
ZTEST_V-VERZE .
ZTEST-MATNR =
ZTEST_V-MATNR .
    IF SY-SUBRC = 0.
    UPDATE ZTEST ##WARN_OK.
    ELSE.
    INSERT ZTEST .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZTEST_V-UPD_FLAG,
STATUS_ZTEST_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZTEST_V.
  SELECT SINGLE * FROM ZTEST WHERE
ID = ZTEST_V-ID AND
VERZE = ZTEST_V-VERZE .
ZTEST_V-MANDT =
ZTEST-MANDT .
ZTEST_V-ID =
ZTEST-ID .
ZTEST_V-VERZE =
ZTEST-VERZE .
ZTEST_V-MATNR =
ZTEST-MATNR .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZTEST_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZTEST_V-ID TO
ZTEST-ID .
MOVE ZTEST_V-VERZE TO
ZTEST-VERZE .
MOVE ZTEST_V-MANDT TO
ZTEST-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTEST'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTEST TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTEST'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
